site_name: GitHub API Package

repo_url: https://github.com/ONS-Innovation/github-api-package
repo_name: GitHub API Package

nav:
  - Home: 'index.md'
  - Documentation: 'documentation.md'
  - Reference:
    - get_token_as_installation: 'reference/get_token_as_installation.md'
    - github_interface: 'reference/github_interface.md'
    - github_graphql_interface: 'reference/github_graphql_interface.md'
  - Example Use Cases:
    - Getting a Repository Owner: 'example_use_cases/getting_a_repository_owner.md'
  
theme:
  name: material
  language: en

  palette:
    # toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

  features:
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer

    - search.suggest

    - header.autohide
    - content.code.copy

  

  logo: assets/logo.png
  favicon: assets/favicon.ico

  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format